[package]
name = "target-gen"
version = "0.1.0"
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs/probe-rs", version = "0.2.0" }
probe-rs-targets = { path = "../probe-rs/probe-rs-targets", version = "0.2.0" }
cmsis-pack = { path = "../cmsis-pack-manager/rust/cmsis-pack" }
goblin = "*"
scroll = "*"
num-traits = "*"
num-derive = "*"
serde = "1.0.101"
serde_yaml = "*"
log = "0.4.8"